/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/admin/audit": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["list_1"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/flags/{flagId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: operations["delete_1"];
        options?: never;
        head?: never;
        patch: operations["update_1"];
        trace?: never;
    };
    "/api/v1/admin/flags/{flagId}/toggle": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["toggle"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/groups": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["list"];
        put?: never;
        post: operations["create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/groups/{groupId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["get"];
        put?: never;
        post?: never;
        delete: operations["delete"];
        options?: never;
        head?: never;
        patch: operations["update"];
        trace?: never;
    };
    "/api/v1/admin/groups/{groupId}/flags": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["create_1"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/token": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["token"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/evaluate/flags": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["all"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/evaluate/flags/{groupKey}/{flagKey}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["flag"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/evaluate/groups/{groupKey}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["group"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        AllFlags: {
            flags: {
                [key: string]: boolean;
            };
            /** Format: int64 */
            revision: number;
        };
        AuditEventView: {
            action: string;
            actor: string;
            details?: {
                [key: string]: unknown;
            };
            /** Format: int64 */
            id: number;
            /** Format: date-time */
            occurredAt: string;
            targetKey: string;
        };
        CreateFlagRequest: {
            description?: string | null;
            enabled?: boolean;
            key: string;
        };
        CreateGroupRequest: {
            description?: string | null;
            key: string;
            name: string;
        };
        Flag: {
            /** Format: date-time */
            createdAt: string;
            createdBy: string;
            description?: string;
            enabled: boolean;
            fullKey: string;
            /** Format: uuid */
            groupId: string;
            /** Format: uuid */
            id: string;
            key: string;
            /** Format: date-time */
            updatedAt: string;
            updatedBy: string;
            /** Format: int64 */
            version: number;
        };
        Group: {
            /** Format: date-time */
            createdAt: string;
            createdBy: string;
            description?: string;
            /** Format: uuid */
            id: string;
            key: string;
            name: string;
            /** Format: date-time */
            updatedAt: string;
            updatedBy: string;
            /** Format: int64 */
            version: number;
        };
        GroupDetail: {
            /** Format: date-time */
            createdAt: string;
            createdBy: string;
            description?: string;
            flags: components["schemas"]["Flag"][];
            /** Format: uuid */
            id: string;
            key: string;
            name: string;
            /** Format: date-time */
            updatedAt: string;
            updatedBy: string;
            /** Format: int64 */
            version: number;
        };
        GroupFlags: {
            flags: {
                [key: string]: boolean;
            };
            group: string;
            /** Format: int64 */
            revision: number;
        };
        GroupSummary: {
            createdBy: string;
            description?: string;
            /** Format: int64 */
            enabledCount: number;
            /** Format: int64 */
            flagCount: number;
            /** Format: uuid */
            id: string;
            key: string;
            name: string;
            /** Format: date-time */
            updatedAt: string;
            updatedBy: string;
            /** Format: int64 */
            version: number;
        };
        LoginRequest: {
            password: string;
            username: string;
        };
        OneFlag: {
            enabled: boolean;
            key: string;
        };
        PageMetadata: {
            /** Format: int64 */
            number: number;
            /** Format: int64 */
            size: number;
            /** Format: int64 */
            totalElements: number;
            /** Format: int64 */
            totalPages: number;
        };
        PagedModelAuditEventView: {
            content: components["schemas"]["AuditEventView"][];
            page: components["schemas"]["PageMetadata"];
        };
        ToggleFlagRequest: {
            enabled: boolean;
        };
        UpdateFlagRequest: {
            description?: string | null;
            enabled?: boolean;
            /** Format: int64 */
            version: number;
        };
        UpdateGroupRequest: {
            description?: string | null;
            name?: string;
            /** Format: int64 */
            version: number;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    list_1: {
        parameters: {
            query?: {
                page?: string;
                size?: string;
                targetKey?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["PagedModelAuditEventView"];
                };
            };
        };
    };
    delete_1: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                flagId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    update_1: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                flagId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateFlagRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["Flag"];
                };
            };
        };
    };
    toggle: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                flagId: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["ToggleFlagRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["Flag"];
                };
            };
        };
    };
    list: {
        parameters: {
            query?: {
                q?: string;
                sort?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["GroupSummary"][];
                };
            };
        };
    };
    create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateGroupRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["Group"];
                };
            };
        };
    };
    get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                groupId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["GroupDetail"];
                };
            };
        };
    };
    delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                groupId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                groupId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateGroupRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["Group"];
                };
            };
        };
    };
    create_1: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                groupId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateFlagRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["Flag"];
                };
            };
        };
    };
    login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": Record<string, never>;
                };
            };
        };
    };
    token: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": Record<string, never>;
                };
            };
        };
    };
    all: {
        parameters: {
            query?: never;
            header?: {
                "If-None-Match"?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Current values */
            200: {
                headers: {
                    /** @description no-cache */
                    "Cache-Control"?: unknown;
                    /** @description "<revision>" */
                    ETag?: unknown;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AllFlags"];
                };
            };
            /** @description Not modified (If-None-Match matches) */
            304: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AllFlags"];
                };
            };
            /** @description Missing, expired or invalid token */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AllFlags"];
                };
            };
            /** @description Token without flags:read / feature-flag-service */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AllFlags"];
                };
            };
        };
    };
    flag: {
        parameters: {
            query?: never;
            header?: {
                "If-None-Match"?: string;
            };
            path: {
                groupKey: string;
                flagKey: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Current values */
            200: {
                headers: {
                    /** @description no-cache */
                    "Cache-Control"?: unknown;
                    /** @description "<revision>" */
                    ETag?: unknown;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OneFlag"];
                };
            };
            /** @description Not modified (If-None-Match matches) */
            304: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OneFlag"];
                };
            };
            /** @description Missing, expired or invalid token */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OneFlag"];
                };
            };
            /** @description Token without flags:read / feature-flag-service */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OneFlag"];
                };
            };
            /** @description Unknown key */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OneFlag"];
                };
            };
        };
    };
    group: {
        parameters: {
            query?: never;
            header?: {
                "If-None-Match"?: string;
            };
            path: {
                groupKey: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Current values */
            200: {
                headers: {
                    /** @description no-cache */
                    "Cache-Control"?: unknown;
                    /** @description "<revision>" */
                    ETag?: unknown;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GroupFlags"];
                };
            };
            /** @description Not modified (If-None-Match matches) */
            304: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GroupFlags"];
                };
            };
            /** @description Missing, expired or invalid token */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GroupFlags"];
                };
            };
            /** @description Token without flags:read / feature-flag-service */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GroupFlags"];
                };
            };
            /** @description Unknown key */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GroupFlags"];
                };
            };
        };
    };
}
