package com.example.featureflags.common;

import static org.assertj.core.api.Assertions.assertThat;

import java.time.Clock;
import java.time.Instant;
import java.time.ZoneOffset;
import java.util.UUID;
import org.junit.jupiter.api.Test;

/** Spec 4.1: ids generated by the application, UUIDv7. */
class UuidV7Test {

  @Test
  void hasVersion7VariantAndTheClockTimestamp() {
    Instant now = Instant.parse("2026-10-01T14:32:05.123Z");
    UUID id = new UuidV7(Clock.fixed(now, ZoneOffset.UTC)).next();

    assertThat(id.version()).isEqualTo(7);
    assertThat(id.variant()).isEqualTo(2);
    assertThat(id.getMostSignificantBits() >>> 16).isEqualTo(now.toEpochMilli());
  }

  @Test
  void laterTimeSortsAfterEarlierTime() {
    Instant t = Instant.parse("2026-10-01T14:32:05.123Z");
    UUID first = new UuidV7(Clock.fixed(t, ZoneOffset.UTC)).next();
    UUID second = new UuidV7(Clock.fixed(t.plusMillis(1), ZoneOffset.UTC)).next();

    assertThat(second.toString()).isGreaterThan(first.toString());
  }

  @Test
  void idsAreUnique() {
    UuidV7 gen = new UuidV7(Clock.fixed(Instant.EPOCH, ZoneOffset.UTC));
    assertThat(gen.next()).isNotEqualTo(gen.next());
  }
}
